### ISSUE TITLE
Schema for structured content with possible values

### ISSUE THREAD

**Issue by marpe** [stephenmk/Jitendex#116]
Is there something like a JSON schema available for the structured content in glossary? Specifically I'm interested in the possible values for e.g `title` in e.g an object like this:
```JSON
[
                    {
                      "tag": "th",
                      "style": {
                        "fontWeight": "normal"
                      },
                      "content": "おなじ"
                    },
                    {
                      "tag": "td",
                      "style": {
                        "textAlign": "center"
                      },
                      "content": {
                        "tag": "div",
                        "title": "valid form/reading combination",
                        "style": {
                          "cursor": "help",
                          "padding": "0 0.25em",
                          "color": "var(--background-color, var(--canvas, #f8f9fa))",
                          "background": "radial-gradient(var(--text-color, var(--fg, #333)) 50%, white 100%)",
                          "clipPath": "circle()",
                          "fontWeight": "bold"
                        },
                        "content": "◇"
                      }
                    }
                  ]
```
I'm using this to build CSS selectors like `div[title="valid form/reading combination"]`. Preferably I would like a version with all of the inline styles removed and instead replaced with classnames that I can override.

**Comment by stephenmk** [comment]
I want to [replace the inline styles with classes](https://github.com/stephenmk/Jitendex/issues/104), but support for CSS stylesheets in yomitan is still in its infancy and [broken](https://github.com/yomidevs/yomitan/issues/1500) in more than one way.

I don't recommend creating styles attached to title tooltip text, since I might decided to change this text sometime. There are some [data attribute properties](https://github.com/stephenmk/Jitendex/wiki/Custom-Styles-in-Yomitan) in the yomitan version that should be fairly stable and you can use to select elements for styles.
