### ISSUE TITLE
Confusing English translation in example sentence for 野山

### ISSUE THREAD

**Issue by Morgawr** [stephenmk/Jitendex#12]
I've been trying to pay more attention to the example sentences provided just so I can try and contribute to the project, but I'm not sure if filing issues here is the best place. If not, please let me know what would be a better place.

Anyway in the entry for 野山:

> 馬の背にまたがり野山を走り回った。
> I rode around the country on horseback.

I think "country" is very misleading here, without context/understanding of what the sentence is actually saying it sounds like going around a "state" or "nation" rather than "country" as in the "countryside" meaning. 

The minimum change that I think would be acceptable in this sentence is to change "country" to "countryside". I still think "countryside" doesn't quite work as well for 野山 but it's an adequate translation at least.

**Comment by stephenmk** [comment]
Well there's an [error reporting category](https://github.com/stephenmk/Jitendex/discussions/categories/errors-and-corrections) in the github discussions tab now. There's not much of a difference whether things are reported here or there (I get notified just the same either way), but that's technically the designated place for it now.

> The minimum change that I think would be acceptable...

If there's a better translation that you'd like to see, feel free to include it as well. The few Japanese-to-English dictionaries that I have all define 野山 as some variation of "fields and mountains" or "fields and hills" which are pretty direct translations. Since those are already glosses in the JMdict entry, I think "countryside" is okay to have in the example sentence.

I added a new translation "*I rode all over the countryside on horseback.*" and linked it to the JMdict sentence. The process for updating the sentences is slower than regular JMdict updates (which occur daily), so it might be a couple weeks before the change shows up in a new version of Jitendex.

Thanks for the report.
