### ISSUE TITLE
Steps to reproduce a yomichan-like setup for goldendict utilizing this dictionary!

### ISSUE THREAD

**Issue by RyanOrigens** [stephenmk/Jitendex#27]
My problem is that Goldendict is bloated. Getting to a point where I have a setup similar to Yomichan would be painful. However, since this would run on my entire computer rather than only in the web browser, I would be willing to try. If you can provide the setup from the screenshot, I would be grateful.

**Comment by stephenmk** [comment]
Rather than using goldendict as a replacement for yomichan, I personally use it for the features that yomichan doesn't have. It can do full-text searches of the bodies of entries, it lets you browse a list of dictionary headwords, and it lets you keep bookmarks. Plus it's easier to develop and test dictionaries in goldendict (it uses HTML & CSS rather than yomichan's restricted JSON format).

So as far as making a setup similar to yomichan, there's not really any information I can share to help. I only use [GoldenDict-ng](https://github.com/xiaoyifang/goldendict-ng) with the "article display style" set to "Babylon" in the application preferences, but I haven't done anything else to customize my setup. You might have better luck asking in the [discussions forum for GoldenDict-ng](https://github.com/xiaoyifang/goldendict-ng/discussions).
