### ISSUE TITLE
Add data-sc-content="examples"

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/Jitendex#4]
The new version of JMdict had `data-sc-content="examples"` so it was possible to hide sentences within Anki

**Comment by stephenmk** [comment]
Compared to the previous version of JMdict that I developed, I cut back on the amount of `data` attributes because I hoped it would [speed up the dictionary validation process when importing the dictionary](https://github.com/FooSoft/yomichan/issues/2138).  Unfortunately it doesn't seem to have made much of a difference. It's not difficult to add them back when people really want them.

I do encourage you to give the sentences a chance. There are some unnatural sentences, but there are just as many that are quite helpful for clarifying the nuances of words. I think they do more good than harm.

I just updated the Yomichan dictionary [in the latest release](https://github.com/stephenmk/Jitendex/releases/tag/v1.2-1) with a new file that applies the data tags to the sentences. The JA sentences have `data-sc-content=example-sentence-a` and the EN sentences have  `data-sc-content=example-sentence-b`. You can hide them both with one selector by using some special [attribute selector syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) .

```css
[data-sc-content|="example-sentence"] {
  display: none;
}
```

**Comment by parfait8566** [comment]
Thanks! 

Yeah, I definitely agree. It's just that I rarely need them when reviewing on Anki and if I ever did I can open the editor and check them. They're certainly useful when looking up words on Yomichan.
