### ISSUE TITLE
Not white-on-black "可" symbol

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/Jitendex#46]
Old table:
![image](https://github.com/stephenmk/Jitendex/assets/146892521/b50937b6-3526-4088-8044-fe380c6462dd)

New table:
![image](https://github.com/stephenmk/Jitendex/assets/146892521/d0efb58b-afe3-4f19-97b5-1600a77100dd)

Also, it looks quite a bit weird on Anki. I guess it's harder to make it look right without svg files.

**Comment by parfait8566** [comment]
Another thing: wouldn't it better to invert the position of forms and readings in the tables?

**Comment by stephenmk** [comment]
I thought about using the color variables exposed by Yomitan's stylesheets to change the colors of that symbol when the user switches between light and dark themes. I didn't get around to trying it and I figured it was good enough as it was, but I agree it looked better before.

I just reuploaded a new version of Jitendex 4.0 for Yomitan which updates the colors on that symbol. Apologies to everyone who already downloaded and installed it.

The Yomitan color variables aren't exported to Anki, so you'll have to set the color variables on your Anki cards if you want the inverted effect. Otherwise it will still look like your second screenshot.

```css
.card {
    /* reverse these colors if you're using a light theme */
    --text-color: white; 
    --background-color: black;
}
```

> wouldn't it better to invert the position of forms and readings in the tables?

Definitely not. The column width would be much wider and more variable on average. Horizontal space is at a premium in the popup window compared to vertical space.
