### ISSUE TITLE
Hide "forms" section when displayed as a list

### ISSUE THREAD

**Issue by Aridow** [stephenmk/Jitendex#56]
With some words like ヘア or コンピューター, the different forms of the word doesn't display as a table but as a list. The issue is, since the different forms already appear in the entry name, I think it's redundant to have this section in that case.

**Comment by stephenmk** [comment]
The order in which forms appear in the "forms" list roughly corresponds to the frequency of their usages. "ヘア" is considerably more common than "ヘアー", so it is at the top of the list. Likewise for コンピュータ and コンピューター. If I removed a form from the list, then this information would be lost.

I am doing something like what you suggest in the MDict version of Jitendex. The form which appears at the top is not displayed again in the "other forms" list at the bottom. But since the form displayed at the top in Yomitan is always the form that has been searched (rather than the top form), it is not possible to replicate this design in Yomitan.

<details>
<summary>Entry for コンピュータ in GoldenDict-ng</summary>

![computer](https://github.com/stephenmk/Jitendex/assets/8003332/6740ab0e-c791-4dd4-b63b-63dbc5c72350)
</details>

<details>
<summary>Entry for ヘア in GoldenDict-ng</summary>

![hair](https://github.com/stephenmk/Jitendex/assets/8003332/eb60a67e-dc65-4e7c-b7d2-4cd4e1056706)
</details>

**Comment by stephenmk** [comment]
Also, I am already hiding the forms list when an entry only contains one form.

![kizen](https://github.com/stephenmk/Jitendex/assets/8003332/d4dafafb-75ec-47e0-80eb-0bd2f14a5605)

**Comment by stephenmk** [comment]
If you still don't want to see the lists, you can add this custom style to your Yomitan to hide them. If you don't know how to do that, I wrote about how to add custom styles to Yomitan [in this article](https://github.com/stephenmk/Jitendex/wiki/Custom-Styles-in-Yomitan).

```css
/* Hide lists of forms in Jitendex */
div[data-sc-content="forms"]:has(ul) {
  display: none;
}
```

**Comment by Aridow** [comment]
Thanks. I just had to remove "div" for it to work.

**Comment by stephenmk** [comment]
That's very surprising to me. I tested it in Chromium and Firefox and it worked with the "div" in both browsers. Are you using a different browser?

**Comment by Aridow** [comment]
I use Firefox. For instance, with the "div", the list is correctly hidden with コンピューター but not with ヘア. In "inspect element" with ヘア it's: `<li class="gloss-sc-li" data-sc-content="forms">`

**Comment by stephenmk** [comment]
Thanks, that makes sense. Because the entry for ヘア has two senses (① and ②), I structured it a little differently. Glad to hear you got it working.
