### ISSUE TITLE
No definitions if the term uses only irregular kanji

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/Jitendex#8]
Not sure if I got something wrong, but "亡う" doesn't give any definitions (excluding the `gikun-form` tag) when it should, just redirects to うしなう.

Also, in my opinion the bright red "誤" for irregular forms is a bit misleading:
![image](https://github.com/stephenmk/Jitendex/assets/146892521/e3bf3875-a1dc-443b-b835-a6b74a14251f)
Irregular forms aren't necessarily mistakes. "喪う" might be much rarer relatively, but it's still deliberately used often and I wouldn't classify it as a mistake (as one could assume seeing the "誤"

**Comment by stephenmk** [comment]
Did you come across "亡う" in a real piece of writing, or were you just browsing headwords in the dictionary? Of the references that I have access to, I only see the form mentioned in 大辞林.

In a [corpus of web pages](https://www.edrdg.org/~jwb/ngramcounts.html) scraped by Google in 2007, ["亡う" was practically never used at all](https://www.edrdg.org/~jwb/cgi-bin/ngramlookup?sent=%E5%A4%B1%E3%81%86%EF%BC%9B%E5%A4%B1%E3%81%AA%E3%81%86%EF%BC%9B%E5%96%AA%E3%81%86%EF%BC%9B%E5%96%AA%E3%81%AA%E3%81%86%EF%BC%9B%E4%BA%A1%E3%81%86%EF%BC%9B%E3%81%86%E3%81%97%E3%81%AA%E3%81%86).

```
Google N-gram Corpus Counts
╭─ーーーーー─┬───────────┬───────╮
│ 失う　　　 │ 1,498,421 │ 98.9% │
│ 喪う　　　 │     5,757 │  0.4% │
│ 失なう　　 │     4,057 │  0.3% │
│ 亡う　　　 │       132 │  0.0% │
│ 喪なう　　 │        53 │  0.0% │
│ うしなう　 │     7,217 │  0.5% │
├─ーーーーー─┼───────────┼───────┤
│ 失った　　 │ 1,717,671 │ 98.2% │
│ 喪った　　 │    14,821 │  0.8% │
│ 失なった　 │     4,186 │  0.2% │
│ 亡った　　 │       601 │  0.0% │
│ 喪なった　 │        41 │  0.0% │
│ うしなった │    11,845 │  0.7% │
╰─ーーーーー─┴───────────┴───────╯
```

 > Also, in my opinion the bright red "誤" for irregular forms is a bit misleading:

JMdict generally tries to avoid taking a prescriptive stance. It prefers to label unofficial sorts of usages as "irregular" or "non-standard" rather than "incorrect", "errors", or "mistakes." The various 国語辞典, on the other hand, don't hesitate to label non-standard spellings and meanings as "誤り." I don't have my heart 100% set on using "誤" in the red circles in the tables, but it seemed like the best choice. I guess we could use something more neutral like an exclamation mark or a "⚠" symbol. But if something in JMdict is tagged as "irregular" and it isn't an "誤り," maybe it should just be changed in JMdict.

"誤り" sorts of spellings usually get the "irregular" tag in JMdict, but it's not always a one-to-one correspondence. The "rare kanji" tag was only introduced in JMdict a couple years ago. Before then, forms like  "喪う" might have been tagged as "irregular" to indicate that they were rare. I just [submitted an edit](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1319750) to have it changed to "rare." 

> "亡う" doesn't give any definitions (excluding the gikun-form tag) when it should, just redirects to うしなう.

The redirects are normal. Since "亡う" is the only kanji form in that entry and since that kanji form is tagged as "irregular," my program assumed that "うしなう" must therefore be the "regular" form. This is not a correct assumption in this case, but I don't think "亡う" should be tagged as "irregular" to begin with. I've submitted an edit to change it.

**Comment by parfait8566** [comment]
> Did you come across "亡う" in a real piece of writing, or were you just browsing headwords in the dictionary?

I found it reading a visual novel (they often have very rare kanji/readings for dramatic purposes). The entry having a `gikun-form` tag caught my interest and afterwards I did check the word in Jisho (which should also use the JMdict database) and thought this might have been a bug.

> "誤り" sorts of spellings usually get the "irregular" tag in JMdict, but it's not always a one-to-one correspondence. The "rare kanji" tag was only introduced in JMdict a couple years ago. Before then, forms like "喪う" might have been tagged as "irregular" to indicate that they were rare. I just [submitted an edit](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1319750) to have it changed to "rare."

I see. In that case I agree with you and "誤" is probably the best choice.

> The redirects are normal. Since "亡う" is the only kanji form in that entry and since that kanji form is tagged as "irregular," my program assumed that "うしなう" must therefore be the "regular" form. This is not a correct assumption in this case, but I don't think "亡う" should be tagged as "irregular" to begin with. I've submitted an edit to change it.

Here I still think the dictionary should reflect JMdict data and provide definitions (not just redirects) to entries with only one irregular-tagged kanji form but I understand your reasoning.

**Comment by parfait8566** [comment]
> I don't think it's correct to say that the dictionary doesn't reflect JMdict data.
JMdict is just a database. It's up to app designers to decide how to present the info.

Oh yeah absolutely, what I meant is I personally think that if JMdict provides definitions "right away" without any redirects the dictionary should do so as well. Either way this is obviously a very minor nitpick.

**Comment by stephenmk** [comment]
> if JMdict provides definitions "right away" without any redirects

What I'm saying is that JMdict does not do this. It's just a database. It doesn't "provide" anything in the same sense that applications "provide" definitions. It's comparing apples and oranges.

> Either way this is obviously a very minor nitpick.

I think it's worth considering. Ideally these redirects should be fairly uncommon. Typically they should be for forms that many other dictionaries don't bother recording as search keys. I think the redirects help emphasize just how non-standard these forms are. They help users arrive at the information that they're really interested in while making it clear how they arrived there.

I guess some people might not like that they have to click through. Some people might have their dictionary client on a separate screen and out of focus. But redirects aren't something that I invented. Lots of dictionaries use them as well as many other types of internal hyperlinks. Normal usage of dictionary clients typically requires quite a lot of scrolling, typing, and clicking, so my hands would tied pretty tightly if I had to design the dictionary for users who can't conveniently click a link.

**Comment by parfait8566** [comment]
> Ideally these redirects should be fairly uncommon.

I actually like redirects, I just think that in this case (where the only kanji form is irregular, though now it has been deleted/merged into "失う") providing the definitions right away seemed more natural (at least in my opinion).
