### ISSUE TITLE
Is there a way to distribute this dictionary without example sentences?

### ISSUE THREAD

**Issue by Morgawr** [stephenmk/Jitendex#9]
Let me preface that I absolutely love and support this project, it's probably my most used dictionary now that I replaced it over the old jmdict. 

This said, I found several inaccuracies or just confusing sentence translations in the example sentences provided. I know it's not a simple task to fix and pretty much every single source I can find out there that takes J-E example sentence translations has this problem, and I think it's unreasonable to be able to solve this for this dictionary as well, however I think it would be nice if there was a release that simply didn't have the example sentences (or at least their English translation). It's not a big deal for me since I just ignore them, but still.

**Comment by Morgawr** [comment]
Oh this is a great short-term solution, thanks!

**Comment by FragozoLeonardo** [comment]
The sentences can be proofreaded, I'm at like N3-N2 level and already can spot flaws even in Japanese sentences, but it's not Stephen's fault, rather than it, it's the original resource (Tanaka Corpus).

some meanings are messed up even in commoun words like 渋い

**Comment by stephenmk** [comment]
There are a few reasons why I don't want a sentence-less version. 

1. It's annoying to have to build and upload multiple versions. I'd rather not unless there's a very compelling reason.
2. More version choices increases the complexity of installation for new users. Having fewer choices is more streamlined.
3. As mentioned by parfait8566, there's a method available for hiding the sentences if users really don't want to see them. Anki, yomi* web extensions, and [goldendict-ng](https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/) all support style customizations.

And most importantly, I want people to see the sentences. It is a herculean task to proofread all the sentences in the Tanaka corpus, but this is an open and collaborative project. Errors that get reported can be fixed, and the errors that people bother to report are more likely to be important ones. If more people see these sentences, the quality will gradually improve.

For example, in a separate GitHub issue I recently posted [an image](https://user-images.githubusercontent.com/8003332/275292954-a16474a1-70db-4962-b360-4ecdad975d23.png) of the entry for わずらう in which the first example sentence was under the wrong definition. [This has been fixed](https://user-images.githubusercontent.com/8003332/279469213-64886ccd-1fbb-4bf2-aee9-ec362ffcd241.png) in the most recent version of Jitendex. Since FragozoLeonardo just mentioned a similar error in the entry for 渋い, I'll go submit a fix after I finish writing this post. Also, earlier this month I had the translation for the example sentence on sense #11 of こ【子】 changed from *"He was born within the sound of the Bow bells"* to *"He's a genuine Londoner."* The original was so indirect and figurative that I thought it was needlessly confusing. 

I want to say that people should feel free to send me an email or open an issue if they find these types of errors. I am a little worried that people might submit things that aren't actually errors but rather small differences of opinion, which ends up wasting both my time and theirs. See [this recent discussion](https://jisho.org/forum/652524aed5dda73cfb000000-sentence-translation) about a sentence translation on jisho.org, for example. Sometimes Tanaka sentences contain language that is technically correct but sounds a little stiff and unnatural, and that's probably something that can't be helped.

I think Github allows you to add a built-in forum to repos now. Maybe I should open a forum for Jitendex and suggest that people report errors there.

---

A couple more things I want to mention.

1. If you want to hide both the Japanese example sentence and the English translation, you can use this style:

```css
[data-sc-content|="example-sentence"] {
  display: none;
}
```

2. There is an ongoing project named [Jreibun](https://www.tufs.ac.jp/ts/personal/SUZUKI_Tomomi/jreibun/index-jreibun.html) for developing a corpus of high quality Japanese-English example sentences. It hasn't been published yet, but it will be freely licensed (Creative Commons) when it is. There is currently a [preview sample of 407 sentences](https://jisho.org/forum/63fdba73d5dda7188e000002-jreibun-new-example-sentences) from the project on jisho.org. I will definitely be adding these sentences to Jitendex when they become publicly available. (And also some method for distinguishing them from the Tanaka sentences).

**Comment by FragozoLeonardo** [comment]
Whoa, Jreibun sounds much better. I signed up for Chuunagon, but having a translation in a more accessible language is in some cases preferable. Translations can be problematic, especially because they often rely on translations themselves in a significant number of cases. However, some translations are just plainly incorrect, like describing a sober-colored sofa as 'stingy.'

**Comment by Morgawr** [comment]
Thanks so much for the response/explanation, it makes perfect sense. I think having the CSS edit already solves my problem so that's good enough for me :) 

As for having the example sentences altogether so people can see them and catch mistakes... I personally don't agree with the idea because the quality of the Tanaka corpus is really not that good and I'm not sure how many people will actually submit fixes, but I can understand your point of view as well. It feels like a bit of a chicken and egg problem, too many mistakes -> they lower the (perceived) quality of the project -> people don't bother to submit fixes -> mistakes stay around for too long. If everyone submitted fixes, it would definitely be nice though. 

While we're on the topic of weird example sentences, let me point out the entry 朝食後 with the sentence "朝食後、出発しましょう。" having the translation "We shall start after breakfast". I think that "start" in the translation is very confusing (especially without context) as it can be taken as "begin". I think it should be changed to something like "Let's depart after breakfast."  instead (or "We shall depart after breakfast" if you want to keep the "We shall" structure which is not wrong but I think is a bit more unusual)

**Comment by stephenmk** [comment]
> I'm not sure how many people will actually submit fixes

Well, people love complaining. Even if they don't come back here to report an error, maybe they'll ask about it or post a screenshot on a different website. Then I or someone else who knows that these mistakes can be fixed will see the complaint and go fix it.

> I think that "start" in the translation is very confusing

Yes, "start" can be used in a very old fashioned way to mean "depart." [Merriam-Webster](https://www.merriam-webster.com/dictionary/start) has this:

> to begin a course or journey 
> | *started* toward the door'
> just *starting* out

I see the very old Saitō Japanese-English dictionary also has "to start (for home―on a journey)" as a definition for 出発.

Definitely would be better as "depart." Thanks for letting me know.
