### ISSUE TITLE
(Suggestion) Replace Tags with Japanese Terms

### ISSUE THREAD

**Issue by chiascuro** [stephenmk/Jitendex#93]
e.g.
noun -> 名詞
intransitive -> 自動詞
transitive -> 他動詞
proverb -> 諺
(5-dan -> 五段)

In my opinion including 5-dan and 1-dan is a redundant tag as it's self-evident from the verb ending, so the verb/動詞 tag would be enough for verbs

Why would this change make sense? 
- Tags are shorter/take up less space
- helps with immersion
- is more accurate grammatically (transitive/intransitive isn't too accurate of a definition for 自動詞/他動詞 verbs, it's merely a western convention)

**Comment by stephenmk** [comment]
> In my opinion including 5-dan and 1-dan is a redundant tag as it's self-evident from the verb ending

AFAIK it's not self evident that 知る, 減る, 入る, 切る, 返る, 握る, 走る, 遮る, etc. are godan rather than ichidan. It's not self evident that 見る, 魂消る, etc. are ichidan rather than godan.

> Tags are shorter/take up less space

Japanese glyphs are less legible at the same font size as Latin-script characters, especially for people who are beginning to learn Japanese. The tags would take up less horizontal space, but they'd take up more vertical space if I increased the font size to compensate.

> helps with immersion

I think the benefits would be marginal at best. It would be off-putting for beginners and unnecessary for advanced learners who can also use monolingual dictionaries.

> is more accurate grammatically (transitive/intransitive isn't too accurate of a definition for 自動詞/他動詞 verbs, it's merely a western convention)

It's the common western convention. I think the benefit of being consistent with other English-language learning resources outweighs the benefit of using alternative descriptions like "self-move" and "other-move" that are arguably closer to the terms used in Japanese.
